#!/usr/bin/env python3

import io
import mimetypes
import urllib.parse
import zipfile

import orthanc


PLUGIN_NAME = "orthanc-extract-document aka OsiriX/Horos Report Tools"
PLUGIN_VERSION = "1.0"


def extract_document(blob):
    """
    Extract a single document from an EncapsulatedDocument ZIP.
    Returns:
        filename, mime, data
    """

    if len(blob) < 4 or blob[:4] != b"PK\x03\x04":
        raise Exception("EncapsulatedDocument is not a ZIP archive")

    #
    # DICOM OB may contain one padding byte
    #
    try:
        archive = zipfile.ZipFile(io.BytesIO(blob))
    except zipfile.BadZipFile:
        archive = zipfile.ZipFile(io.BytesIO(blob[:-1]))

    files = []

    for info in archive.infolist():

        if info.is_dir():
            continue
        name = info.filename
        files.append(info)

    if len(files) != 1:
        raise Exception(
            "ZIP contains %d files (expected exactly one)" % len(files)
        )

    info = files[0]

    filename = info.filename.split("/")[-1]

    mime = mimetypes.guess_type(filename)[0]
    if mime is None:
        mime = "application/octet-stream"

    data = archive.read(info)

    return filename, mime, data


def extract_document_callback(output, uri, **request):

    try:

        instance = uri.split("/")[-2]

        orthanc.LogInfo(
            "[%s] Extracting document from %s"
            % (PLUGIN_NAME, instance)
        )

        blob = orthanc.RestApiGet(
            "/instances/%s/content/0042,0011" % instance
        )

        filename, mime, data = extract_document(blob)

        #
        # original filename generated by OsiriX/Horos
        #
        output.SetHttpHeader(
            "Content-Disposition",
            "attachment; filename*=UTF-8''%s"
            % urllib.parse.quote(filename)
        )

        output.SetHttpHeader(
            "Cache-Control",
            "no-store"
        )

        output.SetHttpHeader(
            "X-Content-Type-Options",
            "nosniff"
        )

        output.AnswerBuffer(data, mime)

    except Exception as e:

        orthanc.LogError(
            "[%s] %s" % (PLUGIN_NAME, str(e))
        )

        output.SendHttpStatusCode(404)


orthanc.RegisterRestCallback(
    "/instances/(.*)/extract-document",
    extract_document_callback
)

orthanc.LogWarning(
    "%s %s loaded"
    % (PLUGIN_NAME, PLUGIN_VERSION)
)
